package com.matthewperiut.aether.item;

import com.matthewperiut.aether.Aether;
import com.matthewperiut.aether.item.accessory.*;
import com.matthewperiut.aether.item.misc.*;
import com.matthewperiut.aether.item.tool.*;
import com.periut.accessoryapi.api.AccessoryRegister;
import com.periut.retroapi.register.item.RetroItemAccess;
import net.minecraft.item.Item;
import net.minecraft.item.ToolMaterial;

public class AetherItems {
    public static final String MOD_ID = Aether.MOD_ID;
    public static Item VictoryMedal;
    public static Item Key;
    public static Item LoreBook;
    public static Item MoaEgg;
    public static Item AechorPetal;
    public static Item GoldenAmber;
    public static Item Stick;
    public static Item Dart;
    public static Item DartShooter;
    public static Item AmbrosiumShard;
    public static Item Zanite;
    public static Item BlueMusicDisk;
    public static Item Bucket;
    public static Item PickSkyroot;
    public static Item PickHolystone;
    public static Item PickZanite;
    public static Item PickGravitite;
    public static Item ShovelSkyroot;
    public static Item ShovelHolystone;
    public static Item ShovelZanite;
    public static Item ShovelGravitite;
    public static Item AxeSkyroot;
    public static Item AxeHolystone;
    public static Item AxeZanite;
    public static Item AxeGravitite;
    public static Item SwordSkyroot;
    public static Item SwordHolystone;
    public static Item SwordZanite;
    public static Item SwordGravitite;
    public static Item IronBubble;
    public static Item PigSlayer;
    public static Item VampireBlade;
    public static Item NatureStaff;
    public static Item SwordFire;
    public static Item SwordLightning;
    public static Item SwordHoly;
    public static Item LightningKnife;
    public static Item GummieSwet;
    public static Item HammerNotch;
    public static Item PhoenixBow;
    public static Item PhoenixHelm;
    public static Item PhoenixBody;
    public static Item PhoenixLegs;
    public static Item PhoenixBoots;
    public static Item ObsidianHelm;
    public static Item ObsidianBody;
    public static Item ObsidianLegs;
    public static Item ObsidianBoots;
    public static Item CloudStaff;
    public static Item CloudParachute;
    public static Item CloudParachuteGold;
    public static Item GravititeHelmet;
    public static Item GravititeBodyplate;
    public static Item GravititePlatelegs;
    public static Item GravititeBoots;
    public static Item ZaniteHelmet;
    public static Item ZaniteChestplate;
    public static Item ZaniteLeggings;
    public static Item ZaniteBoots;
    public static Item LifeShard;
    public static Item GoldenFeather;
    public static Item Lance;
    public static Item RepShield;
    public static Item AetherCape;
    public static Item IronRing;
    public static Item GoldRing;
    public static Item ZaniteRing;
    public static Item IronPendant;
    public static Item GoldPendant;
    public static Item ZanitePendant;
    public static Item LeatherGlove;
    public static Item IronGlove;
    public static Item GoldGlove;
    public static Item DiamondGlove;
    public static Item ZaniteGlove;
    public static Item GravititeGlove;
    public static Item PhoenixGlove;
    public static Item ObsidianGlove;
    public static Item NeptuneGlove;
    public static Item NeptuneHelmet;
    public static Item NeptuneChestplate;
    public static Item NeptuneLeggings;
    public static Item NeptuneBoots;
    public static Item RegenerationStone;
    public static Item InvisibilityCloak;
    public static Item AxeValkyrie;
    public static Item PickValkyrie;
    public static Item ShovelValkyrie;
    public static Item HealingStone;
    public static Item AgilityCape;
    public static Item WhiteCape;
    public static Item RedCape;
    public static Item YellowCape;
    public static Item BlueCape;
    public static Item IceRing;
    public static Item IcePendant;

    private static Item reg(Item item, String name) {
        return RetroItemAccess.of(item).register(Aether.id(name));
    }

    private static int nid() {
        return RetroItemAccess.allocateId();
    }

    public static void registerItems() {
        AccessoryRegister.add("pendant");
        AccessoryRegister.add("cape");
        AccessoryRegister.add("shield");
        AccessoryRegister.add("misc", 0, 3);
        AccessoryRegister.add("misc", 1, 3);
        AccessoryRegister.add("ring");
        AccessoryRegister.add("ring");
        AccessoryRegister.add("gloves");

        VictoryMedal = reg(new Item(nid()).setMaxCount(10), "victory_medal");
        Key = reg(new ItemAetherKey(), "aether_key");
        LoreBook = reg(new ItemLoreBook().setTextureId(59), "lore_book");
        MoaEgg = reg(new ItemMoaEgg(), "moa_egg");
        AechorPetal = reg(new Item(nid()), "aechor_petal");
        GoldenAmber = reg(new Item(nid()), "golden_amber");
        Stick = reg(new Item(nid()), "skyroot_stick");
        Dart = reg(new ItemDart().setHasSubtypes(true), "dart");
        DartShooter = reg(new ItemDartShooter(), "dart_shooter");
        AmbrosiumShard = reg(new ItemAmbrosium(1, false), "ambrosium");
        HealingStone = reg(new ItemAmbrosium(4, false), "healing_stone");
        Zanite = reg(new Item(nid()), "zanite");
        BlueMusicDisk = reg(new ItemAetherRecord("aether:aethertune", "Noisestorm - Aethertune"), "blue_music_disc");
        Bucket = reg(new ItemSkyrootBucket(), "skyroot_bucket");

        ToolMaterial mat = ToolMaterial.WOOD;
        SwordSkyroot = reg(new net.minecraft.item.SwordItem(nid(), mat), "skyroot_sword");
        PickSkyroot = reg(new net.minecraft.item.PickaxeItem(nid(), mat), "skyroot_pickaxe");
        AxeSkyroot = reg(new net.minecraft.item.AxeItem(nid(), mat), "skyroot_axe");
        ShovelSkyroot = reg(new net.minecraft.item.ShovelItem(nid(), mat), "skyroot_shovel");

        mat = ToolMaterial.STONE;
        SwordHolystone = reg(new ItemSwordHolystone(mat), "holystone_sword");
        PickHolystone = reg(new ItemHolystonePickaxe(mat), "holystone_pickaxe");
        AxeHolystone = reg(new ItemHolystoneAxe(mat), "holystone_axe");
        ShovelHolystone = reg(new ItemHolystoneShovel(mat), "holystone_shovel");

        mat = ToolMaterial.IRON;
        SwordZanite = reg(new ItemZaniteSword(mat), "zanite_sword");
        PickZanite = reg(new ItemZanitePickaxe(mat), "zanite_pickaxe");
        AxeZanite = reg(new ItemZaniteAxe(mat), "zanite_axe");
        ShovelZanite = reg(new ItemZaniteShovel(mat), "zanite_shovel");

        mat = ToolMaterial.DIAMOND;
        SwordGravitite = reg(new ItemSwordGravitite(mat), "gravitite_sword");
        PickGravitite = reg(new ItemGravititePickaxe(mat), "gravitite_pickaxe");
        AxeGravitite = reg(new ItemGravititeAxe(mat), "gravitite_axe");
        ShovelGravitite = reg(new ItemGravititeShovel(mat), "gravitite_shovel");

        Lance = reg(new ItemLance(mat), "lance");
        PickValkyrie = reg(new ItemValkyriePickaxe(mat), "valkyrie_pickaxe");
        AxeValkyrie = reg(new ItemValkyrieAxe(mat), "valkyrie_axe");
        ShovelValkyrie = reg(new ItemValkyrieSpade(mat), "valkyrie_shovel");

        PigSlayer = reg(new ItemPigSlayer(), "pig_slayer");
        VampireBlade = reg(new ItemVampireBlade(), "vampire_blade");
        NatureStaff = reg(new Item(nid()).setMaxCount(1), "nature_staff");
        SwordFire = reg(new ItemSwordElemental(EnumElement.Fire, -20609), "fire_sword");
        SwordHoly = reg(new ItemSwordElemental(EnumElement.Holy, -81), "holy_sword");
        SwordLightning = reg(new ItemSwordElemental(EnumElement.Lightning, -5242881), "lightning_sword");
        LightningKnife = reg(new ItemLightningKnife(), "lightning_knife");
        GummieSwet = reg(new ItemGummieSwet(20, false), "gummie_swet");
        HammerNotch = reg(new ItemNotchHammer(), "hammer_notch");
        CloudStaff = reg(new ItemCloudStaff(), "cloud_staff");
        PhoenixBow = reg(new ItemPhoenixBow(), "phoenix_bow");
        PhoenixHelm = reg(new ItemPhoenixArmour(3, "Phoenix", 0, 16742144).setTextureId(1), "item_phoenix_helmet");
        PhoenixBody = reg(new ItemPhoenixArmour(3, "Phoenix", 1, 16742144).setTextureId(17), "item_phoenix_body");
        PhoenixLegs = reg(new ItemPhoenixArmour(3, "Phoenix", 2, 16742144).setTextureId(33), "item_phoenix_legs");
        PhoenixBoots = reg(new ItemPhoenixArmour(3, "Phoenix", 3, 16742144).setTextureId(49), "item_phoenix_boots");
        ObsidianHelm = reg(new ItemColouredArmour(4, "Obsidian", 0, 1774663).setTextureId(2), "item_obsidian_helmet");
        ObsidianBody = reg(new ItemColouredArmour(4, "Obsidian", 1, 1774663).setTextureId(18), "item_obsidian_body");
        ObsidianLegs = reg(new ItemColouredArmour(4, "Obsidian", 2, 1774663).setTextureId(34), "item_obsidian_legs");
        ObsidianBoots = reg(new ItemColouredArmour(4, "Obsidian", 3, 1774663).setTextureId(50), "item_obsidian_boots");
        GravititeHelmet = reg(new ItemColouredArmour(3, "Gravitite", 0, 15160027).setTextureId(2), "item_gravitite_helmet");
        GravititeBodyplate = reg(new ItemColouredArmour(3, "Gravitite", 1, 15160027).setTextureId(18), "item_gravitite_body");
        GravititePlatelegs = reg(new ItemColouredArmour(3, "Gravitite", 2, 15160027).setTextureId(34), "item_gravitite_legs");
        GravititeBoots = reg(new ItemColouredArmour(3, "Gravitite", 3, 15160027).setTextureId(50), "item_gravitite_boots");
        ZaniteHelmet = reg(new ItemColouredArmour(2, "Zanite", 0, 7412456).setTextureId(2), "item_zanite_helmet");
        ZaniteChestplate = reg(new ItemColouredArmour(2, "Zanite", 1, 7412456).setTextureId(18), "item_zanite_body");
        ZaniteLeggings = reg(new ItemColouredArmour(2, "Zanite", 2, 7412456).setTextureId(34), "item_zanite_legs");
        ZaniteBoots = reg(new ItemColouredArmour(2, "Zanite", 3, 7412456).setTextureId(50), "item_zanite_boots");
        NeptuneHelmet = reg(new ItemColouredArmour(3, "Neptune", 0, 2512127).setTextureId(1), "item_neptune_helmet");
        NeptuneChestplate = reg(new ItemColouredArmour(3, "Neptune", 1, 2512127).setTextureId(17), "item_neptune_body");
        NeptuneLeggings = reg(new ItemColouredArmour(3, "Neptune", 2, 2512127).setTextureId(33), "item_neptune_legs");
        NeptuneBoots = reg(new ItemColouredArmour(3, "Neptune", 3, 2512127).setTextureId(49), "item_neptune_boots");
        LifeShard = reg(new ItemLifeShard(), "life_shard");
        GoldenFeather = reg(new ItemGoldenFeather(0, 0, 7), "golden_feather");
        IronBubble = reg(new ItemIronBubble(0, 0, 7), "iron_bubble");
        RegenerationStone = reg(new ItemRegenerationStone(0, 0, 7), "regeneration_stone");
        RepShield = reg(new ItemRepShield(0, 0, 6, 16777215).setMaxDamage(512), "repulsion_shield");
        IronRing = reg(new ItemMoreArmor(0, "aether:textures/armor/Accessories.png", 8, 16777215), "iron_ring");
        GoldRing = reg(new ItemMoreArmor(0, "aether:textures/armor/Accessories.png", 8, 16776994), "gold_ring");
        ZaniteRing = reg(new ItemMoreArmor(0, "aether:textures/armor/Accessories.png", 8, 7412456), "zanite_ring");
        IceRing = reg(new ItemIceAccessory(0, "aether:textures/armor/Accessories.png", 8, 9823975), "ice_ring");
        IronPendant = reg(new ItemPendant(0, "aether:textures/armor/Accessories.png", 4, 16777215), "iron_pendant");
        GoldPendant = reg(new ItemPendant(0, "aether:textures/armor/Accessories.png", 4, 16776994), "gold_pendant");
        ZanitePendant = reg(new ItemPendant(0, "aether:textures/armor/Accessories.png", 4, 7412456), "zanite_pendant");
        IcePendant = reg(new ItemIcePendant(0, "aether:textures/armor/Accessories.png", 4, 9823975), "ice_pendant");
        AetherCape = reg(new ItemCape(0, "aether:textures/other/AetherCape.png", 5), "aether_cape");
        InvisibilityCloak = reg(new ItemInvisibilityCloak(0, 0, 5), "invisibility_cloak");
        AgilityCape = reg(new ItemAgilityCape(0, "aether:textures/other/AgilityCape.png", 5), "agility_cape");
        WhiteCape = reg(new ItemCape(0, "aether:textures/other/WhiteCape.png", 5), "white_cape");
        RedCape = reg(new ItemCape(0, "aether:textures/other/RedCape.png", 5, 15208721), "red_cape");
        YellowCape = reg(new ItemCape(0, "aether:textures/other/YellowCape.png", 5, 13486862), "yellow_cape");
        BlueCape = reg(new ItemCape(0, "aether:textures/other/BlueCape.png", 5, 1277879), "blue_cape");
        LeatherGlove = reg(new ItemGloves(0, "aether:textures/armor/Accessories.png", 10, 12999733), "leather_glove");
        IronGlove = reg(new ItemGloves(2, "aether:textures/armor/Accessories.png", 10, 14540253), "iron_glove");
        GoldGlove = reg(new ItemGloves(1, "aether:textures/armor/Accessories.png", 10, 15396439), "gold_glove");
        DiamondGlove = reg(new ItemGloves(3, "aether:textures/armor/Accessories.png", 10, 3402699), "diamond_glove");
        ZaniteGlove = reg(new ItemGloves(2, "aether:textures/armor/Accessories.png", 10, 7412456), "zanite_glove");
        GravititeGlove = reg(new ItemGravititeGlove(3, "aether:textures/armor/Accessories.png", 10, 15160027), "gravitite_glove");
        PhoenixGlove = reg(new ItemPhoenixGloves(3, "aether:textures/armor/Phoenix.png", 10, 16742144, false), "phoenix_glove");
        ObsidianGlove = reg(new ItemGloves(4, "aether:textures/armor/Accessories.png", 10, 1774663), "obsidian_glove");
        NeptuneGlove = reg(new ItemGloves(3, "aether:textures/armor/Accessories.png", 10, 2512127), "neptune_glove");
        CloudParachute = reg(new ItemCloudParachute(false), "cloud_parachute");
        CloudParachuteGold = reg(new ItemCloudParachute(true), "cloud_parachute_gold");
    }
}
