# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx1G
org.gradle.parallel=true

# Fabric Properties
	# check these on https://babric.github.io/develop/
	minecraft_version=b1.7.3
    yarn_mappings=b1.7.3+4cbd9c8
    loader_version=0.18.4

# Mod Properties
	mod_version = 1.5.0
	maven_group = com.matthewperiut
	archives_base_name = aether
    retroapi_version=1.0.19
    osl_version = 0.17.2
	mixinextras_version=0.2.2

# Test properties
	gcapi_version = 3.3.0+gen2
	glass_networking_version=1.0.7
    alwaysmoreitems_version=1.7.1
	spawneggs_version=1.11.0
    modmenu_version=1.8.5-beta.11
	retrocommands_version = 0.7.1+gen2
	accessory_version = 0.8.0+gen2
	bhcreative_version = 0.4.10+gen2
	starac_version=1.2.1+mcb1.7.3+gen2

# Runtime Dependencies
	mojang_fix_stapi_version=2.4.4

# Added by babric2ornithe
biny_mappings = 9859f76
client_raven_build = 2
server_raven_build = 2
client_sparrow_build = 2
server_sparrow_build = 2
