package com.matthewperiut.aether.optional;

import com.matthewperiut.aether.block.AetherBlocks;
import com.matthewperiut.aether.item.AetherItems;
import net.mine_diver.unsafeevents.listener.EventListener;
import net.minecraft.item.ItemStack;
import paulevs.bhcreative.api.CreativeTab;
import paulevs.bhcreative.api.SimpleTab;
import paulevs.bhcreative.registry.TabRegistryEvent;

import static com.matthewperiut.aether.item.AetherItems.MOD_ID;

public class AetherCreativeListener {
    public static CreativeTab aetherBlocks;
    public static CreativeTab aetherItems;

    @EventListener
    public void onTabInit(TabRegistryEvent event) {
        aetherBlocks = new SimpleTab(MOD_ID.id("aetherBlocks"), new ItemStack(AetherBlocks.Grass)); // Making tab
        event.register(aetherBlocks);
        aetherBlocks.addItem(new ItemStack(AetherBlocks.Portal));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.Dirt));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.Grass));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.WhiteFlower));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.PurpleFlower));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.Quicksoil));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.Holystone, 1, 1));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.Holystone, 1, 3));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.Icestone));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.Aercloud, 1, 0));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.Aercloud, 1, 1));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.Aercloud, 1, 2));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.Aerogel));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.Log, 1, 1));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.Log, 1, 2));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.Plank));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.SkyrootLeaves));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.GoldenOakLeaves));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.SkyrootSapling));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.GoldenOakSapling));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.AmbrosiumOre));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.AmbrosiumTorch));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.BurntTorch));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.ZaniteOre));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.GravititeOre));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.EnchantedGravitite));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.Enchanter));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.Incubator));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.Trap));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.ChestMimic));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.Chest));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.TreasureChest));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.DungeonStone, 1, 0));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.DungeonStone, 1, 1));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.DungeonStone, 1, 2));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.LightDungeonStone, 1, 0));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.LightDungeonStone, 1, 1));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.LightDungeonStone, 1, 2));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.LockedDungeonStone, 1, 0));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.LockedDungeonStone, 1, 1));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.LockedDungeonStone, 1, 2));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.LockedLightDungeonStone, 1, 0));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.LockedLightDungeonStone, 1, 1));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.LockedLightDungeonStone, 1, 2));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.Pillar, 1, 0));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.Pillar, 1, 1));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.Pillar, 1, 2));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.ZaniteBlock));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.QuicksoilGlass));
        aetherBlocks.addItem(new ItemStack(AetherBlocks.Freezer));

        aetherItems = new SimpleTab(MOD_ID.id("aetherItems"), new ItemStack(AetherItems.GoldenFeather)); // Making tab
        event.register(aetherItems);
        aetherItems.addItem(new ItemStack(AetherItems.VictoryMedal));
        aetherItems.addItem(new ItemStack(AetherItems.Key, 1, 0));
        aetherItems.addItem(new ItemStack(AetherItems.Key, 1, 1));
        aetherItems.addItem(new ItemStack(AetherItems.Key, 1, 2));
        aetherItems.addItem(new ItemStack(AetherItems.LoreBook, 1, 0));
        aetherItems.addItem(new ItemStack(AetherItems.LoreBook, 1, 1));
        aetherItems.addItem(new ItemStack(AetherItems.LoreBook, 1, 2));
        aetherItems.addItem(new ItemStack(AetherItems.MoaEgg, 1, 0));
        aetherItems.addItem(new ItemStack(AetherItems.MoaEgg, 1, 1));
        aetherItems.addItem(new ItemStack(AetherItems.MoaEgg, 1, 2));
        aetherItems.addItem(new ItemStack(AetherItems.AechorPetal));
        aetherItems.addItem(new ItemStack(AetherItems.GoldenAmber));
        aetherItems.addItem(new ItemStack(AetherItems.Stick));
        aetherItems.addItem(new ItemStack(AetherItems.Dart, 1, 0));
        aetherItems.addItem(new ItemStack(AetherItems.Dart, 1, 1));
        aetherItems.addItem(new ItemStack(AetherItems.Dart, 1, 2));
        aetherItems.addItem(new ItemStack(AetherItems.DartShooter, 1, 0));
        aetherItems.addItem(new ItemStack(AetherItems.DartShooter, 1, 1));
        aetherItems.addItem(new ItemStack(AetherItems.DartShooter, 1, 2));
        aetherItems.addItem(new ItemStack(AetherItems.AmbrosiumShard));
        aetherItems.addItem(new ItemStack(AetherItems.Zanite));
        aetherItems.addItem(new ItemStack(AetherItems.BlueMusicDisk));
        aetherItems.addItem(new ItemStack(AetherItems.Bucket, 1, 0));
        aetherItems.addItem(new ItemStack(AetherItems.Bucket, 1, 8));
        aetherItems.addItem(new ItemStack(AetherItems.Bucket, 1, 1));
        aetherItems.addItem(new ItemStack(AetherItems.Bucket, 1, 2));
        aetherItems.addItem(new ItemStack(AetherItems.Bucket, 1, 3));
        aetherItems.addItem(new ItemStack(AetherItems.PickSkyroot));
        aetherItems.addItem(new ItemStack(AetherItems.PickHolystone));
        aetherItems.addItem(new ItemStack(AetherItems.PickZanite));
        aetherItems.addItem(new ItemStack(AetherItems.PickGravitite));
        aetherItems.addItem(new ItemStack(AetherItems.ShovelSkyroot));
        aetherItems.addItem(new ItemStack(AetherItems.ShovelHolystone));
        aetherItems.addItem(new ItemStack(AetherItems.ShovelZanite));
        aetherItems.addItem(new ItemStack(AetherItems.ShovelGravitite));
        aetherItems.addItem(new ItemStack(AetherItems.AxeSkyroot));
        aetherItems.addItem(new ItemStack(AetherItems.AxeHolystone));
        aetherItems.addItem(new ItemStack(AetherItems.AxeZanite));
        aetherItems.addItem(new ItemStack(AetherItems.AxeGravitite));
        aetherItems.addItem(new ItemStack(AetherItems.SwordSkyroot));
        aetherItems.addItem(new ItemStack(AetherItems.SwordHolystone));
        aetherItems.addItem(new ItemStack(AetherItems.SwordZanite));
        aetherItems.addItem(new ItemStack(AetherItems.SwordGravitite));
        aetherItems.addItem(new ItemStack(AetherItems.IronBubble));
        aetherItems.addItem(new ItemStack(AetherItems.PigSlayer));
        aetherItems.addItem(new ItemStack(AetherItems.VampireBlade));
        aetherItems.addItem(new ItemStack(AetherItems.NatureStaff));
        aetherItems.addItem(new ItemStack(AetherItems.SwordFire));
        aetherItems.addItem(new ItemStack(AetherItems.SwordLightning));
        aetherItems.addItem(new ItemStack(AetherItems.SwordHoly));
        aetherItems.addItem(new ItemStack(AetherItems.LightningKnife));
        aetherItems.addItem(new ItemStack(AetherItems.GummieSwet));
        aetherItems.addItem(new ItemStack(AetherItems.HammerNotch));
        aetherItems.addItem(new ItemStack(AetherItems.PhoenixBow));
        aetherItems.addItem(new ItemStack(AetherItems.PhoenixHelm));
        aetherItems.addItem(new ItemStack(AetherItems.PhoenixBody));
        aetherItems.addItem(new ItemStack(AetherItems.PhoenixLegs));
        aetherItems.addItem(new ItemStack(AetherItems.PhoenixBoots));
        aetherItems.addItem(new ItemStack(AetherItems.ObsidianHelm));
        aetherItems.addItem(new ItemStack(AetherItems.ObsidianBody));
        aetherItems.addItem(new ItemStack(AetherItems.ObsidianLegs));
        aetherItems.addItem(new ItemStack(AetherItems.ObsidianBoots));
        aetherItems.addItem(new ItemStack(AetherItems.CloudStaff));
        aetherItems.addItem(new ItemStack(AetherItems.CloudParachute));
        aetherItems.addItem(new ItemStack(AetherItems.CloudParachuteGold));
        aetherItems.addItem(new ItemStack(AetherItems.GravititeHelmet));
        aetherItems.addItem(new ItemStack(AetherItems.GravititeBodyplate));
        aetherItems.addItem(new ItemStack(AetherItems.GravititePlatelegs));
        aetherItems.addItem(new ItemStack(AetherItems.GravititeBoots));
        aetherItems.addItem(new ItemStack(AetherItems.ZaniteHelmet));
        aetherItems.addItem(new ItemStack(AetherItems.ZaniteChestplate));
        aetherItems.addItem(new ItemStack(AetherItems.ZaniteLeggings));
        aetherItems.addItem(new ItemStack(AetherItems.ZaniteBoots));
        aetherItems.addItem(new ItemStack(AetherItems.LifeShard));
        aetherItems.addItem(new ItemStack(AetherItems.GoldenFeather));
        aetherItems.addItem(new ItemStack(AetherItems.Lance));
        aetherItems.addItem(new ItemStack(AetherItems.RepShield));
        aetherItems.addItem(new ItemStack(AetherItems.AetherCape));
        aetherItems.addItem(new ItemStack(AetherItems.IronRing));
        aetherItems.addItem(new ItemStack(AetherItems.GoldRing));
        aetherItems.addItem(new ItemStack(AetherItems.ZaniteRing));
        aetherItems.addItem(new ItemStack(AetherItems.IronPendant));
        aetherItems.addItem(new ItemStack(AetherItems.GoldPendant));
        aetherItems.addItem(new ItemStack(AetherItems.ZanitePendant));
        aetherItems.addItem(new ItemStack(AetherItems.LeatherGlove));
        aetherItems.addItem(new ItemStack(AetherItems.IronGlove));
        aetherItems.addItem(new ItemStack(AetherItems.GoldGlove));
        aetherItems.addItem(new ItemStack(AetherItems.DiamondGlove));
        aetherItems.addItem(new ItemStack(AetherItems.ZaniteGlove));
        aetherItems.addItem(new ItemStack(AetherItems.GravititeGlove));
        aetherItems.addItem(new ItemStack(AetherItems.PhoenixGlove));
        aetherItems.addItem(new ItemStack(AetherItems.ObsidianGlove));
        aetherItems.addItem(new ItemStack(AetherItems.NeptuneGlove));
        aetherItems.addItem(new ItemStack(AetherItems.NeptuneHelmet));
        aetherItems.addItem(new ItemStack(AetherItems.NeptuneChestplate));
        aetherItems.addItem(new ItemStack(AetherItems.NeptuneLeggings));
        aetherItems.addItem(new ItemStack(AetherItems.NeptuneBoots));
        aetherItems.addItem(new ItemStack(AetherItems.RegenerationStone));
        aetherItems.addItem(new ItemStack(AetherItems.InvisibilityCloak));
        aetherItems.addItem(new ItemStack(AetherItems.AxeValkyrie));
        aetherItems.addItem(new ItemStack(AetherItems.PickValkyrie));
        aetherItems.addItem(new ItemStack(AetherItems.ShovelValkyrie));
        aetherItems.addItem(new ItemStack(AetherItems.HealingStone));
        aetherItems.addItem(new ItemStack(AetherItems.AgilityCape));
        aetherItems.addItem(new ItemStack(AetherItems.WhiteCape));
        aetherItems.addItem(new ItemStack(AetherItems.RedCape));
        aetherItems.addItem(new ItemStack(AetherItems.YellowCape));
        aetherItems.addItem(new ItemStack(AetherItems.BlueCape));
        aetherItems.addItem(new ItemStack(AetherItems.IceRing));
        aetherItems.addItem(new ItemStack(AetherItems.IcePendant));
    }

}
